Repository osmhpi/cohydra, pull requests merged in 2020-02, with the labels that each got.

#7 Adds inheritance diagrams to documentation
  .devcontainer/Dockerfile
  docs/source/_templates/autosummary/package.rst
  docs/source/conf.py
  testbed/channel/wifi.py
  testbed/command_executor/docker.py
  testbed/command_executor/ssh.py
  testbed/mobility_input/mobility_input.py
  testbed/mobility_input/sumo.py
  testbed/node/base.py
  testbed/scenario.py
Labels: documentation

#21 Docs: Setup Pipeline
  .github/workflows/pull_request-opened.yml
  .gitignore
  .travis-scripts/docs.sh
  .travis.yml
  Makefile
  docs/Makefile
  docs/requirements.txt
  docs/source/_templates/autosummary/package.rst
  docs/source/api.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/modules.rst
Labels: documentation

#26 Docker container names with _ and .
  cohydra/node/base.py
  cohydra/node/docker.py
Labels: enhancement

#27 Remove Python exception on Ctrl C during simulation
  cohydra/simulation.py
  examples/basic_example.py
  examples/bridge_example.py
  examples/networking_demo.py
  examples/sawtooth.py
  examples/sawtooth_pbft.py
  examples/ssh_example.py
  examples/sumo_example.py
  examples/volumes_and_ports_example.py
  examples/webserver_example.py
  examples/wifi_example.py
Labels: bug
